In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
from sklearn.model_selection import train_test_split
X = df.drop(['species'],axis=1)
Y = df['species']
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,random_state=42,test_size=0.2)

In [8]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train,Y_train)
y_predict = gnb.predict(X_test)

In [10]:
from sklearn.metrics import accuracy_score,confusion_matrix

acc = accuracy_score(Y_test,y_predict)
print(f"Accuracy of the model is {acc*100}%")
cm = confusion_matrix(Y_test,y_predict)
print("Confusion Matrix \n\n",cm)

Accuracy of the model is 100.0%
Confusion Matrix 

 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [11]:
y_pred_train = gnb.predict(X_train)
acc_train = accuracy_score(Y_train,y_pred_train)


In [12]:
print(f"Accuracy of training dataset: {acc_train*100}% \n Accuracy of testing: {acc*100}%")

Accuracy of training dataset: 95.0% 
 Accuracy of testing: 100.0%
