In [1]:
import pandas as pd
import numpy as np
import seaborn as sns


In [2]:
df = sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
X = df.drop(['species'],axis=1)
Y = df['species']

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=42)
X_test,X_val,Y_test,Y_val = train_test_split(X_test,Y_test,random_state=42,test_size=0.5)
print("Size of training dataset:",X_train.shape)
print("Size of testing dataset:",X_test.shape)
print("Size of validating dataset:",X_val.shape)

Size of training dataset: (105, 4)
Size of testing dataset: (22, 4)
Size of validating dataset: (23, 4)


In [9]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
knn = KNeighborsClassifier()
parameters = {'n_neighbors':[1,2,3,4,5,6,7,8]}
clf = GridSearchCV(knn,parameters,scoring='accuracy')
clf.fit(X_train,Y_train)
print("Best parameter for k:",clf.best_params_)
print("Best accuracy score for K",clf.best_score_)
best_model = clf.best_estimator_



Best parameter for k: {'n_neighbors': 1}
Best accuracy score for K 0.9523809523809523


In [11]:
from sklearn.metrics import accuracy_score,confusion_matrix
y_pred_train = best_model.predict(X_train)
acc_train = accuracy_score(Y_train,y_pred_train)
cm_train = confusion_matrix(Y_train,y_pred_train)
print("Accuracy score for training data: ",acc_train)
print("Confusion matrix for training data\n\n",cm_train)

y_pred_test = best_model.predict(X_test)
acc_test = accuracy_score(Y_test,y_pred_test)
cm_test = confusion_matrix(Y_test,y_pred_test)
print("Accuracy score for testing data: ",acc_test)
print("Confusion matrix for testing data\n\n",cm_test)

y_pred_val = best_model.predict(X_val)
acc_val = accuracy_score(Y_val,y_pred_val)
cm_val = confusion_matrix(Y_val,y_pred_val)
print("Accuracy score for validation data: ",acc_val)
print("Confusion matrix for validation data\n\n",cm_val)


Accuracy score for training data:  1.0
Confusion matrix for training data

 [[31  0  0]
 [ 0 37  0]
 [ 0  0 37]]
Accuracy score for testing data:  1.0
Confusion matrix for testing data

 [[13  0  0]
 [ 0  3  0]
 [ 0  0  6]]
Accuracy score for validation data:  1.0
Confusion matrix for validation data

 [[ 6  0  0]
 [ 0 10  0]
 [ 0  0  7]]
