In [10]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

# Step 1: Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Step 2: Preprocess the data
# No preprocessing required for this dataset

# Step 3: Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Define the logistic regression model and train it on the training data
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Step 5: Make predictions on the testing data
y_pred = model.predict(X_test)

# Step 6: Calculate the confusion matrix, sensitivity, and specificity
conf_matrix = confusion_matrix(y_test, y_pred)
TN, FP, FN, TP, *rem = conf_matrix.ravel()

sensitivity = TP / (TP + FN)
specificity = TN / (TN + FP)

# Step 7: Print the confusion matrix, sensitivity, and specificity
print("Confusion Matrix:")
print(conf_matrix)
print("\nSensitivity:", sensitivity)
print("Specificity:", specificity)


Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Sensitivity: nan
Specificity: 1.0


/var/folders/w2/h2dz2yy55hl6hqpfnylt2l4c0000gn/T/ipykernel_31807/3029095206.py:30: RuntimeWarning: invalid value encountered in scalar divide
  sensitivity = TP / (TP + FN)
